# Generated by Django 4.2.6 on 2023-10-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Bishkek'), (2, 'Osh')], default=1),
        ),
    ]
